### PR TITLE
correctly handle thrown errors

### LINKED ISSUE #27: java-rx-smgrsdk may cause requests to time out when raising errors
some errors cause the framework to throw exceptions. These are not handled correctly and no response is sent to the requester. Eventually the request times out.

### PR DESCRIPTION
**Pull request by mer2github**
Any throw went unhandled until the vert.x layer which meant no response was sent back over our socket connection

Fixes #27

### CODE REVIEW

File: java-rx-smgrsdk/src/main/java/io/vantiq/svcconnector/StorageManagerVerticle.java [hunk 1]
```diff
@@ -81,116 +81,119 @@ public Completable rxStop() {
...
-                                msg.procName));
-                    } else {
-                        //noinspection unchecked
-                        result = storageManager.initializeTypeDefinition(
-                                (Map<String, Object>) msg.params.get("proposedType"),
-                                (Map<String, Object>) msg.params.get("existingType")
+        try {
+            if (msg.procName != null) {
+                // procedure name is <package name>.<service name>.<procedure name>
+                String[] parts = msg.procName.split("\\.");
```
Comment (jcguion) [inline java-rx-smgrsdk/src/main/java/io/vantiq/svcconnector/StorageManagerVerticle.java:87]: seems like Git got quite confused by the indentation...

**Review by jcguion — APPROVED** [review]
LGTM

File: java-rx-smgrsdk/src/main/java/io/vantiq/svcconnector/StorageManagerVerticle.java (hunk 1 above)
Comment (mer2github) [reply java-rx-smgrsdk/src/main/java/io/vantiq/svcconnector/StorageManagerVerticle.java:87]: sorry, the diff looked more reasonable in the IDE
